//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGV
{
    using System;
    using System.Collections.Generic;
    
    public partial class AGVRegist
    {
        public string AGVName { get; set; }
        public string RegisterName { get; set; }
        public string AGVIP { get; set; }
        public string AGVPort { get; set; }
        public string CamIP { get; set; }
        public string CamPort { get; set; }
        public string Map { get; set; }
        public int Num { get; set; }
    }
}
